/**
 * task3_iconnect
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PostView } from './postView';

export interface UsersView { 
    id?: number;
    firstName?: string;
    lastName?: string;
    age?: number;
    dateOfBirthday?: Date;
    email?: string;
    posts?: Array<PostView>;
}